---
title: "ooi-carbonate-setup"
author: "Kate Morkeski"
date: "1/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#load required packages #TODO: switch from require to library
require(tidyverse) 
require(httr)
require(readxl)
require(here)

#set path to root of project
here("ooi-carbonate-setup")

```

## Access OOI data from Alfresco

```{r}


# Pioneer 14 Sampling Log Version 1-01
log_url <- ('https://alfresco.oceanobservatories.org/alfresco/webdav/OOI/Coastal%20Pioneer%20Array/Cruise%20Data/Pioneer-14_AR44_2020-06-07/Ship%20Data/Water%20Sampling/Pioneer-14_AR44_CTD_Sampling_Log_2020-12-07_Ver_1-01.xlsx')

# Pioneer 14 salinity data Version 1-01
sal_url <- ('https://alfresco.oceanobservatories.org/alfresco/webdav/OOI/Coastal%20Pioneer%20Array/Cruise%20Data/Pioneer-14_AR44_2020-06-07/Ship%20Data/Water%20Sampling/Pioneer-14_AR44_Salinity_Sample_Data_2020-12-07_Ver_1-01.xlsx')


```


```{r}

# Supply credentials for Alfresco
creds <- read_file("authenticate.txt")
#creds <- read_csv("authenticate.csv")

httr::GET(log_url, authenticate(creds, creds), write_disk(logtf <- tempfile(fileext = ".xlsx")))

logtf

httr::GET(sal_url, authenticate(creds, creds), write_disk(saltf <- tempfile(fileext = ".xlsx")))

saltf

```

## Read in Excel file from Alfresco and format cruise ID and column headers

```{r}

log <- read_excel(logtf, 1L) 
sal <- read_excel(saltf, 1L) 

```

# count DICTA and pH bottles

```{r}

n_distinct(log$`DIC/TA Bottle #`, na.rm = TRUE)
n_distinct(log$`Ph Bottle #`, na.rm = TRUE)

```
```{r}

bottles <- log %>%
  rename(Cruise_ID = "Cruise ID") %>%
  rename(station = "Station-Cast #") %>%
  rename(niskin = "Niskin #") %>%
  rename(PH_bottle = "Ph Bottle #") %>%
  rename(DICTA_bottle = "DIC/TA Bottle #") %>%
  rename(salt_bottle = "Salts Bottle #") 
 
bottles$station <- as.numeric(bottles$station)
bottles$niskin <- as.numeric(bottles$niskin)

headers <- c("Cruise_ID", "station", "niskin", "Date", "PH_bottle", "DICTA_bottle", "salt_bottle")
bottles <- bottles[, headers]

sal <- sal %>%
  rename(station = "Station ID") %>%
  rename(niskin = "Niskin ID") %>%
  rename(salt_bottle = "Sample ID") %>%
  rename(salinity_psu = "Salinity [psu]")

```

# match salinity to cruise log
# this doesn't work because salt bottle IDs are repeated on Pio 14
```{r}

#bottles$salinity <- NA_integer_ 

#for (i in 1:nrow(bottles)){
  
#  bottles$salinity[i] <- sal$salinity_psu[sal$salt_bottle == bottles$salts_bottle[i]]
  
#}

```

# isolate carbonate rows
# check number of bottles
# join with salinity
```{r}

bottles <- filter(bottles, PH_bottle != "NA" | DICTA_bottle != "NA")

n_distinct(bottles$DICTA_bottle, na.rm = TRUE)
n_distinct(bottles$PH_bottle, na.rm = TRUE)

bottles_sal <- left_join(bottles, sal, c("station", "niskin", "salt_bottle"))

```

# clean up salinity dataframe and write to csv

```{r}

bottles_sal$salinity_psu <- as.numeric(bottles_sal$salinity_psu)

bottles_sal <- bottles_sal %>%
  mutate(salinity_psu = round(salinity_psu, 4))

headers <- c("Cruise_ID", "Date", "DICTA_bottle", "PH_bottle", "salinity_psu")
bottles_sal <- bottles_sal[, headers]

write_csv(bottles_sal, "Pioneer_14_carbonate_bottle_salinity.csv")

```



  

